import {
  IconArchive,
  IconArrowLeft,
  IconArrowUp,
  IconBinaryTree2,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconDots,
  IconDownload,
  IconFile,
  IconFileText,
  IconFileUpload,
  IconFolder,
  IconFolderOpen,
  IconFolderSymlink,
  IconFolderUp,
  IconInfoCircle,
  IconLayoutGrid,
  IconLayoutList,
  IconLibrary,
  IconLibraryMinus,
  IconLibraryPlus,
  IconLink,
  IconLoader2,
  IconMusic,
  IconPencil,
  IconPhoto,
  IconPlayerPlay,
  IconPlus,
  IconSearch,
  IconSelector,
  IconShare2,
  IconSortAZ,
  IconStack2,
  IconTrash,
  IconUpload,
  IconX,
} from '@tabler/icons-react';

import { createEntryIcon } from './entryIcons';

export const RESOURCE_ENTRY_ICONS = {
  all: createEntryIcon(IconLayoutGrid),
  archive: createEntryIcon(IconArchive),
  audios: createEntryIcon(IconMusic),
  back: createEntryIcon(IconArrowLeft),
  calendar: createEntryIcon(IconCalendar),
  check: createEntryIcon(IconCheck),
  chevronDown: createEntryIcon(IconChevronDown),
  chunk: createEntryIcon(IconBinaryTree2),
  close: createEntryIcon(IconX),
  date: createEntryIcon(IconCalendar),
  documents: createEntryIcon(IconFileText),
  download: createEntryIcon(IconDownload),
  edit: createEntryIcon(IconPencil),
  file: createEntryIcon(IconFile),
  fileUpload: createEntryIcon(IconFileUpload),
  folder: createEntryIcon(IconFolder),
  folderMove: createEntryIcon(IconFolderSymlink),
  folderOpen: createEntryIcon(IconFolderOpen),
  folderUpload: createEntryIcon(IconFolderUp),
  grid: createEntryIcon(IconLayoutGrid),
  images: createEntryIcon(IconPhoto),
  info: createEntryIcon(IconInfoCircle),
  sourceSet: createEntryIcon(IconLibrary),
  sourceSetAdd: createEntryIcon(IconLibraryPlus),
  sourceSetRemove: createEntryIcon(IconLibraryMinus),
  link: createEntryIcon(IconLink),
  list: createEntryIcon(IconLayoutList),
  loader: createEntryIcon(IconLoader2),
  more: createEntryIcon(IconDots),
  page: createEntryIcon(IconFileText),
  plus: createEntryIcon(IconPlus),
  search: createEntryIcon(IconSearch),
  selector: createEntryIcon(IconSelector),
  share: createEntryIcon(IconShare2),
  size: createEntryIcon(IconStack2),
  sort: createEntryIcon(IconSortAZ),
  trash: createEntryIcon(IconTrash),
  upload: createEntryIcon(IconUpload),
  uploadArrow: createEntryIcon(IconArrowUp),
  videos: createEntryIcon(IconPlayerPlay),
} as const;
