import i18n from 'i18next';

import {
  createStarterTableMarkdown,
  getDefaultTableColumnName,
  isRecognizedAutoGeneratedTableColumnName,
  parseMarkdownTable,
  serializeTableMarkdown,
  type TableSheetData,
  tableSheetToCsv,
  tableSheetToXlsxBase64,
} from './docsTable';

export const TABLE_DOCUMENT_METADATA_KEY = 'table';
export const TABLE_DOCUMENT_VERSION = 2;

export type TableFieldType = 'checkbox' | 'date' | 'number' | 'select' | 'text' | 'url';
export type TableRowHeight = 'comfortable' | 'compact' | 'normal';
export type TableFilterOperator =
  | 'contains'
  | 'equals'
  | 'greaterThan'
  | 'isEmpty'
  | 'isNotEmpty'
  | 'lessThan'
  | 'notEquals';
export type TableSortDirection = 'asc' | 'desc';

export type TableCellValue = boolean | string;

export interface TableField {
  id: string;
  name: string;
  type: TableFieldType;
  width?: number;
}

export interface TableRecord {
  cells: Record<string, TableCellValue>;
  id: string;
}

export interface TableViewFilter {
  fieldId: string;
  id: string;
  operator: TableFilterOperator;
  value?: string;
}

export interface TableViewSort {
  direction: TableSortDirection;
  fieldId: string;
  id: string;
}

export interface TableView {
  fields: TableField[];
  filters: TableViewFilter[];
  groupByFieldId?: string;
  hiddenFieldIds: string[];
  id: string;
  name: string;
  records: TableRecord[];
  rowHeight: TableRowHeight;
  sorts: TableViewSort[];
  type: 'grid';
}

export interface TableDocumentState {
  activeViewId: string;
  version: number;
  views: TableView[];
}

interface TableDocumentToSheetDataOptions {
  activeViewOnly?: boolean;
  viewId?: string;
}

interface LegacyTableDocumentState {
  activeViewId?: string;
  fields?: unknown[];
  records?: unknown[];
  views?: unknown[];
}

interface TableViewProjection {
  fields: TableField[];
  records: TableRecord[];
  view: TableView;
}

const DEFAULT_FIELD_WIDTH = 200;
const DEFAULT_ROW_HEIGHT: TableRowHeight = 'normal';
const DEFAULT_FIELD_TYPE: TableFieldType = 'text';
const DEFAULT_FIELDS = 5;
const DEFAULT_RECORDS = 8;
const LEGACY_DEFAULT_VIEW_NAME_PATTERN = /^Sheet (\d+)$/;
const LEGACY_UNTITLED_FIELD_NAME = 'Untitled field';

const createId = (prefix: string) =>
  `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

const getDefaultTableViewName = (index = 1) =>
  i18n.t('docEditor.table.sheetDefaultName', {
    defaultValue: `Sheet ${index}`,
    index,
    ns: 'file',
  });

const getUntitledFieldName = () =>
  i18n.t('docEditor.table.untitledFieldName', {
    defaultValue: LEGACY_UNTITLED_FIELD_NAME,
    ns: 'file',
  });

const localizeLegacyViewName = (name: string | undefined, index: number) => {
  const trimmed = name?.trim();

  if (!trimmed) return getDefaultTableViewName(index);

  const legacyMatch = trimmed.match(LEGACY_DEFAULT_VIEW_NAME_PATTERN);
  if (legacyMatch && Number(legacyMatch[1]) === index) {
    return getDefaultTableViewName(index);
  }

  return trimmed;
};

const localizeLegacyFieldName = (name: string | undefined, index: number) => {
  const trimmed = name?.trim();

  if (!trimmed || trimmed === LEGACY_UNTITLED_FIELD_NAME) return getDefaultTableColumnName(index);
  if (index === 0 && trimmed === 'Name') return getDefaultTableColumnName(index);

  const legacyColumnMatch = trimmed.match(/^Column (\d+)$/);
  if (legacyColumnMatch && Number(legacyColumnMatch[1]) === index + 1) {
    return getDefaultTableColumnName(index);
  }

  const legacyFieldMatch = trimmed.match(/^Field (\d+)$/);
  if (legacyFieldMatch && Number(legacyFieldMatch[1]) === index + 1) {
    return getDefaultTableColumnName(index);
  }

  return trimmed;
};

export const createTableField = (
  name: string,
  type: TableFieldType = DEFAULT_FIELD_TYPE,
): TableField => ({
  id: createId('field'),
  name: name.trim() || getUntitledFieldName(),
  type,
  width: DEFAULT_FIELD_WIDTH,
});

export const createTableRecord = (fields: TableField[]): TableRecord => ({
  cells: Object.fromEntries(fields.map((field) => [field.id, getDefaultCellValue(field.type)])),
  id: createId('record'),
});

const createTableViewFromData = (
  fields: TableField[],
  records: TableRecord[],
  name = getDefaultTableViewName(),
): TableView => ({
  fields,
  filters: [],
  groupByFieldId: undefined,
  hiddenFieldIds: [],
  id: createId('view'),
  name,
  records,
  rowHeight: DEFAULT_ROW_HEIGHT,
  sorts: [],
  type: 'grid',
});

export const createDefaultTableView = (
  name = getDefaultTableViewName(),
  fieldCount = DEFAULT_FIELDS,
  recordCount = DEFAULT_RECORDS,
): TableView => {
  const starterSheet = parseMarkdownTable(createStarterTableMarkdown(fieldCount, recordCount));
  const fields = starterSheet.columns.map((column) => createTableField(column.name));
  const records = starterSheet.rows.map((row) => ({
    cells: Object.fromEntries(
      fields.map((field, index) => [
        field.id,
        normalizeTableCellValue(row[`column_${index + 1}`], field.type),
      ]),
    ),
    id: createId('record'),
  }));

  return createTableViewFromData(fields, records, name);
};

export const createDefaultTableDocument = (
  fieldCount = DEFAULT_FIELDS,
  recordCount = DEFAULT_RECORDS,
  name = getDefaultTableViewName(),
): TableDocumentState => {
  const defaultView = createDefaultTableView(name, fieldCount, recordCount);

  return {
    activeViewId: defaultView.id,
    version: TABLE_DOCUMENT_VERSION,
    views: [defaultView],
  };
};

export const appendBlankTableView = (
  table: TableDocumentState,
  name = getDefaultTableViewName(table.views.length + 1),
): TableDocumentState => {
  const nextView = createDefaultTableView(name);

  return {
    ...table,
    activeViewId: nextView.id,
    views: [...table.views, nextView],
  };
};

export const tableDocumentToMarkdown = (
  table: TableDocumentState,
  options?: TableDocumentToSheetDataOptions,
): string => {
  return serializeTableMarkdown(tableDocumentToSheetData(table, options));
};

export const tableDocumentToCsv = (
  table: TableDocumentState,
  options?: TableDocumentToSheetDataOptions,
): string => {
  return tableSheetToCsv(tableDocumentToSheetData(table, options));
};

export const tableDocumentToXlsxBase64 = (
  table: TableDocumentState,
  title?: string,
  options?: TableDocumentToSheetDataOptions,
): string => {
  return tableSheetToXlsxBase64(tableDocumentToSheetData(table, options), title);
};

export const getActiveTableView = (table: TableDocumentState, viewId?: string): TableView => {
  return (
    table.views.find((view) => view.id === viewId) ||
    table.views.find((view) => view.id === table.activeViewId) ||
    table.views[0] ||
    createDefaultTableView()
  );
};

export const projectTableView = (
  table: TableDocumentState,
  viewId?: string,
): TableViewProjection => {
  const view = getActiveTableView(table, viewId);
  const visibleFields = view.fields.filter((field) => !view.hiddenFieldIds.includes(field.id));
  let records = [...view.records];

  for (const filter of view.filters) {
    records = records.filter((record) => matchesFilter(record, view.fields, filter));
  }

  if (view.sorts.length > 0) {
    records.sort((left, right) => compareRecords(left, right, view.fields, view.sorts));
  }

  return {
    fields: visibleFields,
    records,
    view,
  };
};

export const normalizeTableDocument = (
  markdown?: string | null,
  rawValue?: unknown,
  options?: { preferMarkdownContent?: boolean },
): TableDocumentState => {
  const fallbackView = buildViewFromMarkdown(markdown);

  if (isTableDocumentState(rawValue)) {
    return normalizeCurrentTableDocument(rawValue, fallbackView, markdown, options);
  }

  if (isLegacyTableDocumentState(rawValue)) {
    return normalizeLegacyTableDocument(rawValue, fallbackView, markdown, options);
  }

  return {
    activeViewId: fallbackView.id,
    version: TABLE_DOCUMENT_VERSION,
    views: [fallbackView],
  };
};

export const updateTableFieldWidths = (
  table: TableDocumentState,
  widths: Record<string, number>,
): TableDocumentState =>
  mapActiveTableView(table, (view) => ({
    ...view,
    fields: view.fields.map((field) =>
      widths[field.id] ? { ...field, width: widths[field.id] } : field,
    ),
  }));

export const tableDocumentToSheetData = (
  table: TableDocumentState,
  options?: TableDocumentToSheetDataOptions,
): TableSheetData => {
  const view = getActiveTableView(table, options?.viewId);
  const projection = options?.activeViewOnly ? projectTableView(table, view.id) : undefined;
  const fields = projection?.fields || view.fields;
  const records = projection?.records || view.records;

  return {
    columns: fields.map((field) => ({
      key: field.id,
      name: field.name,
    })),
    rows: records.map((record) => ({
      id: record.id,
      ...Object.fromEntries(
        fields.map((field) => [
          field.id,
          formatCellForMarkdown(record.cells[field.id], field.type),
        ]),
      ),
    })),
  };
};

export const getPrimaryField = (table: TableDocumentState | TableView): TableField | undefined => {
  return isTableView(table) ? table.fields[0] : getActiveTableView(table).fields[0];
};

export const getRecordTitle = (table: TableDocumentState | TableView, record?: TableRecord) => {
  if (!record) return '';

  const primaryField = getPrimaryField(table);
  if (!primaryField) return '';

  const value = record.cells[primaryField.id];
  return typeof value === 'boolean' ? (value ? 'True' : 'False') : value || '';
};

export const duplicateTableView = (
  table: TableDocumentState,
  name?: string,
): TableDocumentState => {
  const currentView = getActiveTableView(table);
  const nextView = cloneTableView(currentView, name || `${currentView.name} Copy`);

  return {
    ...table,
    activeViewId: nextView.id,
    views: [...table.views, nextView],
  };
};

export const removeTableView = (table: TableDocumentState, viewId: string): TableDocumentState => {
  if (table.views.length === 1) return table;

  const views = table.views.filter((view) => view.id !== viewId);
  return {
    ...table,
    activeViewId: views.some((view) => view.id === table.activeViewId)
      ? table.activeViewId
      : views[0]!.id,
    views,
  };
};

export const renameActiveTableView = (
  table: TableDocumentState,
  name: string,
): TableDocumentState => ({
  ...table,
  views: table.views.map((view) =>
    view.id === table.activeViewId
      ? { ...view, name: name.trim() || getDefaultTableViewName() }
      : view,
  ),
});

export const setActiveTableView = (
  table: TableDocumentState,
  viewId: string,
): TableDocumentState => {
  if (!table.views.some((view) => view.id === viewId)) return table;
  return { ...table, activeViewId: viewId };
};

const buildViewFromMarkdown = (
  markdown?: string | null,
  name = getDefaultTableViewName(),
): TableView => {
  const sheet = parseMarkdownTable(markdown);
  const fields = sheet.columns.map((column) => createTableField(column.name));
  const records =
    sheet.rows.length > 0
      ? sheet.rows.map((row) => ({
          cells: Object.fromEntries(
            fields.map((field, index) => [
              field.id,
              normalizeTableCellValue(row[`column_${index + 1}`], field.type),
            ]),
          ),
          id: createId('record'),
        }))
      : [createTableRecord(fields)];

  return createTableViewFromData(fields, records, name);
};

const normalizeCurrentTableDocument = (
  rawValue: TableDocumentState,
  fallbackView: TableView,
  markdown?: string | null,
  options?: { preferMarkdownContent?: boolean },
): TableDocumentState => {
  const views = normalizeViews(rawValue.views, fallbackView);
  const activeViewId = views.some((view) => view.id === rawValue.activeViewId)
    ? rawValue.activeViewId
    : views[0]!.id;

  return {
    activeViewId,
    version: TABLE_DOCUMENT_VERSION,
    views: views.map((view) =>
      view.id === activeViewId && options?.preferMarkdownContent
        ? mergeViewWithMarkdown(markdown, view)
        : view,
    ),
  };
};

const normalizeLegacyTableDocument = (
  rawValue: LegacyTableDocumentState,
  fallbackView: TableView,
  markdown?: string | null,
  options?: { preferMarkdownContent?: boolean },
): TableDocumentState => {
  const fields = normalizeFields(rawValue.fields, fallbackView.fields);
  const records =
    options?.preferMarkdownContent ||
    !Array.isArray(rawValue.records) ||
    rawValue.records.length === 0
      ? rebuildRecordsFromMarkdown(markdown, fields, rawValue.records)
      : normalizeRecords(rawValue.records, fields);
  const views = normalizeLegacyViews(rawValue.views, fields, records);
  const activeViewId = views.some((view) => view.id === rawValue.activeViewId)
    ? rawValue.activeViewId!
    : views[0]!.id;

  return {
    activeViewId,
    version: TABLE_DOCUMENT_VERSION,
    views: views.map((view) =>
      view.id === activeViewId && options?.preferMarkdownContent
        ? mergeViewWithMarkdown(markdown, view)
        : view,
    ),
  };
};

const normalizeLegacyViews = (
  rawViews: unknown,
  fields: TableField[],
  records: TableRecord[],
): TableView[] => {
  if (!Array.isArray(rawViews) || rawViews.length === 0) {
    return [
      createTableViewFromData(
        cloneFields(fields),
        cloneRecords(records),
        getDefaultTableViewName(),
      ),
    ];
  }

  return rawViews.map<TableView>((view, index) => {
    const rawView = view as Partial<TableView>;
    const nextView: TableView = {
      fields: cloneFields(fields),
      filters: Array.isArray(rawView.filters)
        ? rawView.filters
            .filter((filter) => filter && typeof filter === 'object')
            .map((filter) => {
              const item = filter as Partial<TableViewFilter>;
              return {
                fieldId: item.fieldId || '',
                id: item.id || createId('filter'),
                operator: normalizeFilterOperator(item.operator),
                value: typeof item.value === 'string' ? item.value : undefined,
              };
            })
            .filter((filter) => !!filter.fieldId)
        : [],
      groupByFieldId:
        typeof rawView.groupByFieldId === 'string' && rawView.groupByFieldId
          ? rawView.groupByFieldId
          : undefined,
      hiddenFieldIds: Array.isArray(rawView.hiddenFieldIds)
        ? rawView.hiddenFieldIds.map((id) => String(id))
        : [],
      id: rawView.id || createId('view'),
      name: localizeLegacyViewName(rawView.name, index + 1),
      records: cloneRecords(records),
      rowHeight: normalizeRowHeight(rawView.rowHeight),
      sorts: Array.isArray(rawView.sorts)
        ? rawView.sorts
            .filter((sort) => sort && typeof sort === 'object')
            .map<TableViewSort>((sort) => {
              const item = sort as Partial<TableViewSort>;
              return {
                direction: item.direction === 'desc' ? 'desc' : 'asc',
                fieldId: item.fieldId || '',
                id: item.id || createId('sort'),
              };
            })
            .filter((sort) => !!sort.fieldId)
        : [],
      type: 'grid',
    };

    return sanitizeTableView(nextView);
  });
};

const normalizeViews = (rawViews: unknown, fallbackView: TableView): TableView[] => {
  if (!Array.isArray(rawViews) || rawViews.length === 0) return [fallbackView];

  return rawViews.map<TableView>((view, index) => {
    const rawView = view as Partial<TableView>;
    const fields = normalizeFields(rawView.fields, fallbackView.fields);
    const records = normalizeRecords(rawView.records, fields);
    const nextView: TableView = {
      fields,
      filters: Array.isArray(rawView.filters)
        ? rawView.filters
            .filter((filter) => filter && typeof filter === 'object')
            .map((filter) => {
              const item = filter as Partial<TableViewFilter>;
              return {
                fieldId: item.fieldId || '',
                id: item.id || createId('filter'),
                operator: normalizeFilterOperator(item.operator),
                value: typeof item.value === 'string' ? item.value : undefined,
              };
            })
            .filter((filter) => !!filter.fieldId)
        : [],
      groupByFieldId:
        typeof rawView.groupByFieldId === 'string' && rawView.groupByFieldId
          ? rawView.groupByFieldId
          : undefined,
      hiddenFieldIds: Array.isArray(rawView.hiddenFieldIds)
        ? rawView.hiddenFieldIds.map((id) => String(id))
        : [],
      id: rawView.id || createId('view'),
      name: localizeLegacyViewName(rawView.name, index + 1),
      records,
      rowHeight: normalizeRowHeight(rawView.rowHeight),
      sorts: Array.isArray(rawView.sorts)
        ? rawView.sorts
            .filter((sort) => sort && typeof sort === 'object')
            .map<TableViewSort>((sort) => {
              const item = sort as Partial<TableViewSort>;
              return {
                direction: item.direction === 'desc' ? 'desc' : 'asc',
                fieldId: item.fieldId || '',
                id: item.id || createId('sort'),
              };
            })
            .filter((sort) => !!sort.fieldId)
        : [],
      type: 'grid',
    };

    return sanitizeTableView(nextView);
  });
};

const normalizeFields = (
  rawFields: unknown[] | undefined,
  fallbackFields: TableField[],
): TableField[] => {
  if (!Array.isArray(rawFields) || rawFields.length === 0) {
    return normalizeAutoGeneratedFieldNames(cloneFields(fallbackFields));
  }

  const normalizedFields = rawFields.map((field, index) => {
    const fallbackField = fallbackFields[index];
    if (!field || typeof field !== 'object') {
      return fallbackField
        ? { ...fallbackField }
        : createTableField(getDefaultTableColumnName(index));
    }

    const normalizedField = field as Partial<TableField>;

    return {
      id: normalizedField.id || fallbackField?.id || createId('field'),
      name:
        localizeLegacyFieldName(normalizedField.name, index) ||
        fallbackField?.name ||
        getDefaultTableColumnName(index),
      type: normalizeFieldType(normalizedField.type),
      width:
        typeof normalizedField.width === 'number'
          ? normalizedField.width
          : fallbackField?.width || DEFAULT_FIELD_WIDTH,
    };
  });

  return normalizeAutoGeneratedFieldNames(normalizedFields);
};

const normalizeRecords = (
  rawRecords: unknown[] | undefined,
  fields: TableField[],
): TableRecord[] => {
  if (!Array.isArray(rawRecords) || rawRecords.length === 0) return [createTableRecord(fields)];

  return rawRecords.map((record) => {
    const nextRecord = record as Partial<TableRecord>;
    const rawCells =
      nextRecord.cells && typeof nextRecord.cells === 'object' ? nextRecord.cells : {};

    return {
      cells: Object.fromEntries(
        fields.map((field) => [
          field.id,
          normalizeTableCellValue((rawCells as Record<string, unknown>)[field.id], field.type),
        ]),
      ),
      id: nextRecord.id || createId('record'),
    };
  });
};

const rebuildRecordsFromMarkdown = (
  markdown: string | null | undefined,
  fields: TableField[],
  rawRecords?: unknown[],
): TableRecord[] => {
  const sheet = parseMarkdownTable(markdown);
  const recordIds =
    Array.isArray(rawRecords) && rawRecords.length > 0
      ? rawRecords.map((record) =>
          record && typeof record === 'object' && 'id' in record
            ? String(record.id)
            : createId('record'),
        )
      : [];

  const rebuilt = sheet.rows.map((row, index) => ({
    cells: Object.fromEntries(
      fields.map((field, fieldIndex) => [
        field.id,
        normalizeTableCellValue(row[`column_${fieldIndex + 1}`], field.type),
      ]),
    ),
    id: recordIds[index] || createId('record'),
  }));

  return rebuilt.length > 0 ? rebuilt : [createTableRecord(fields)];
};

const mergeViewWithMarkdown = (markdown: string | null | undefined, view: TableView): TableView => {
  const markdownView = buildViewFromMarkdown(markdown, view.name);
  const fields = markdownView.fields.map((field, index) => ({
    id: view.fields[index]?.id || field.id,
    name: field.name,
    type: view.fields[index]?.type || field.type,
    width: view.fields[index]?.width || field.width,
  }));

  const records = markdownView.records.map((record, rowIndex) => ({
    cells: Object.fromEntries(
      fields.map((field, fieldIndex) => [
        field.id,
        normalizeTableCellValue(record.cells[markdownView.fields[fieldIndex]!.id], field.type),
      ]),
    ),
    id: view.records[rowIndex]?.id || record.id,
  }));

  return sanitizeTableView({
    ...view,
    fields,
    records: records.length > 0 ? records : [createTableRecord(fields)],
  });
};

const cloneFields = (fields: TableField[]): TableField[] => fields.map((field) => ({ ...field }));

const isRecognizedDefaultFieldName = (name: string, fieldCount: number) => {
  const trimmed = name.trim();
  if (!trimmed) return false;
  if (/^Field \d+$/.test(trimmed)) return true;

  return isRecognizedAutoGeneratedTableColumnName(trimmed, fieldCount);
};

const normalizeAutoGeneratedFieldNames = (fields: TableField[]) => {
  if (fields.length <= 1) return fields;

  const secondaryFields = fields.slice(1);
  if (!secondaryFields.every((field) => isRecognizedDefaultFieldName(field.name, fields.length)))
    return fields;

  return fields.map((field, index) => ({
    ...field,
    name: getDefaultTableColumnName(index),
  }));
};

const cloneRecords = (records: TableRecord[]): TableRecord[] =>
  records.map((record) => ({
    cells: { ...record.cells },
    id: record.id,
  }));

const cloneTableView = (view: TableView, name: string): TableView => {
  const nextFields = view.fields.map((field) => ({ ...field, id: createId('field') }));
  const fieldIdMap = Object.fromEntries(
    view.fields.map((field, index) => [field.id, nextFields[index]!.id]),
  );
  const nextRecords = view.records.map((record) => ({
    cells: Object.fromEntries(
      view.fields.map((field, index) => [
        nextFields[index]!.id,
        normalizeTableCellValue(record.cells[field.id], nextFields[index]!.type),
      ]),
    ),
    id: createId('record'),
  }));

  return sanitizeTableView({
    fields: nextFields,
    filters: view.filters
      .map((filter) => ({
        ...filter,
        fieldId: fieldIdMap[filter.fieldId] || '',
        id: createId('filter'),
      }))
      .filter((filter) => !!filter.fieldId),
    groupByFieldId: view.groupByFieldId ? fieldIdMap[view.groupByFieldId] : undefined,
    hiddenFieldIds: view.hiddenFieldIds
      .map((fieldId) => fieldIdMap[fieldId])
      .filter((fieldId): fieldId is string => !!fieldId),
    id: createId('view'),
    name,
    records: nextRecords,
    rowHeight: view.rowHeight,
    sorts: view.sorts
      .map((sort) => ({
        ...sort,
        fieldId: fieldIdMap[sort.fieldId] || '',
        id: createId('sort'),
      }))
      .filter((sort) => !!sort.fieldId),
    type: 'grid',
  });
};

const sanitizeTableView = (view: TableView): TableView => {
  const validFieldIds = new Set(view.fields.map((field) => field.id));

  return {
    ...view,
    filters: view.filters.filter((filter) => validFieldIds.has(filter.fieldId)),
    groupByFieldId:
      view.groupByFieldId && validFieldIds.has(view.groupByFieldId)
        ? view.groupByFieldId
        : undefined,
    hiddenFieldIds: view.hiddenFieldIds.filter((fieldId) => validFieldIds.has(fieldId)),
    records: normalizeRecords(view.records, view.fields),
    sorts: view.sorts.filter((sort) => validFieldIds.has(sort.fieldId)),
  };
};

const mapActiveTableView = (
  table: TableDocumentState,
  updater: (view: TableView) => TableView,
): TableDocumentState => ({
  ...table,
  views: table.views.map((view) =>
    view.id === table.activeViewId ? sanitizeTableView(updater(view)) : view,
  ),
});

const isTableView = (value: TableDocumentState | TableView): value is TableView => {
  return 'fields' in value && 'records' in value;
};

const isTableDocumentState = (value: unknown): value is TableDocumentState => {
  if (!value || typeof value !== 'object') return false;
  const table = value as Partial<TableDocumentState>;
  return Array.isArray(table.views);
};

const isLegacyTableDocumentState = (value: unknown): value is LegacyTableDocumentState => {
  if (!value || typeof value !== 'object') return false;
  const table = value as Partial<LegacyTableDocumentState>;
  return (
    Array.isArray(table.fields) ||
    Array.isArray(table.records) ||
    typeof table.activeViewId === 'string'
  );
};

const normalizeFieldType = (value?: unknown): TableFieldType => {
  switch (value) {
    case 'checkbox':
    case 'date':
    case 'number':
    case 'select':
    case 'url': {
      return value;
    }
    default: {
      return 'text';
    }
  }
};

const normalizeRowHeight = (value?: unknown): TableRowHeight => {
  switch (value) {
    case 'comfortable':
    case 'compact': {
      return value;
    }
    default: {
      return 'normal';
    }
  }
};

const normalizeFilterOperator = (value?: unknown): TableFilterOperator => {
  switch (value) {
    case 'equals':
    case 'greaterThan':
    case 'isEmpty':
    case 'isNotEmpty':
    case 'lessThan':
    case 'notEquals': {
      return value;
    }
    default: {
      return 'contains';
    }
  }
};

const getDefaultCellValue = (fieldType: TableFieldType): TableCellValue => {
  if (fieldType === 'checkbox') return false;
  return '';
};

export const normalizeTableCellValue = (
  value: unknown,
  fieldType: TableFieldType,
): TableCellValue => {
  if (fieldType === 'checkbox') {
    if (typeof value === 'boolean') return value;
    const normalized = String(value || '')
      .trim()
      .toLowerCase();
    return ['1', 'checked', 'done', 'true', 'yes', 'y'].includes(normalized);
  }

  return String(value ?? '');
};

const formatCellForMarkdown = (
  value: TableCellValue | undefined,
  fieldType: TableFieldType,
): string => {
  if (fieldType === 'checkbox') return value ? 'true' : 'false';
  return String(value ?? '');
};

const matchesFilter = (
  record: TableRecord,
  fields: TableField[],
  filter: TableViewFilter,
): boolean => {
  const field = fields.find((item) => item.id === filter.fieldId);
  if (!field) return true;

  const rawValue = record.cells[field.id];
  const value = field.type === 'checkbox' ? String(Boolean(rawValue)) : String(rawValue ?? '');
  const compareValue = String(filter.value ?? '');

  switch (filter.operator) {
    case 'equals': {
      return value === compareValue;
    }
    case 'greaterThan': {
      return compareAsComparable(field.type, value) > compareAsComparable(field.type, compareValue);
    }
    case 'isEmpty': {
      return !value;
    }
    case 'isNotEmpty': {
      return !!value;
    }
    case 'lessThan': {
      return compareAsComparable(field.type, value) < compareAsComparable(field.type, compareValue);
    }
    case 'notEquals': {
      return value !== compareValue;
    }
    default: {
      return value.toLowerCase().includes(compareValue.toLowerCase());
    }
  }
};

const compareRecords = (
  left: TableRecord,
  right: TableRecord,
  fields: TableField[],
  sorts: TableViewSort[],
): number => {
  for (const sort of sorts) {
    const field = fields.find((item) => item.id === sort.fieldId);
    if (!field) continue;

    const leftValue = compareAsComparable(field.type, left.cells[field.id]);
    const rightValue = compareAsComparable(field.type, right.cells[field.id]);

    if (leftValue === rightValue) continue;

    const result = leftValue > rightValue ? 1 : -1;
    return sort.direction === 'desc' ? result * -1 : result;
  }

  return 0;
};

const compareAsComparable = (fieldType: TableFieldType, value: unknown): number | string => {
  if (fieldType === 'checkbox') return value ? 1 : 0;
  if (fieldType === 'number') return Number(value || 0);
  if (fieldType === 'date') return Date.parse(String(value || '')) || 0;
  return String(value ?? '').toLowerCase();
};
