import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { Buffer } from 'node:buffer';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');

const desktopHtml = readFileSync(resolve(root, 'dist/desktop/index.html'), 'utf8');

const mobileHtmlPath = resolve(root, 'dist/mobile/index.mobile.html');
const mobileHtmlFallbackPath = resolve(root, 'dist/mobile/index.html');
const hasMobileBuild = existsSync(mobileHtmlPath) || existsSync(mobileHtmlFallbackPath);

/** Base64 embed avoids Next.js output file tracing (nft) treating /spa/assets/*.js in the HTML as dist/desktop/** filesystem deps during standalone builds. */
const asBase64Const = (name: string, html: string) =>
  `export const ${name} = Buffer.from(${JSON.stringify(Buffer.from(html, 'utf8').toString('base64'))}, 'base64').toString('utf8');`;

let output: string;

if (hasMobileBuild) {
  // Docker: mobile build exists locally, inline the template
  const mobileHtml = readFileSync(
    existsSync(mobileHtmlPath) ? mobileHtmlPath : mobileHtmlFallbackPath,
    'utf8',
  );

  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

import { Buffer } from 'node:buffer';

${asBase64Const('desktopHtmlTemplate', desktopHtml)}

${asBase64Const('mobileHtmlTemplate', mobileHtml)}
`;
} else {
  // Vercel: no mobile build, import from pre-committed source file
  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

import { Buffer } from 'node:buffer';

import { mobileHtmlTemplate } from './mobileHtmlTemplate.source';

${asBase64Const('desktopHtmlTemplate', desktopHtml)}

export { mobileHtmlTemplate };
`;
}

writeFileSync(
  resolve(root, 'src/app/spa/[variants]/[[...path]]/spaHtmlTemplates.ts'),
  output,
  'utf8',
);

console.log(`Generated spaHtmlTemplates.ts (mobile from ${hasMobileBuild ? 'build' : 'source'})`);
