import { z } from 'zod';

import type { FileParsingTask } from '../asyncTask';

export interface FileUploadState {
  progress: number;
  /**
   * rest time in s
   */
  restTime: number;
  /**
   * upload speed in Byte/s
   */
  speed: number;
}

export type FileUploadStatus =
  | 'pending'
  | 'uploading'
  | 'processing'
  | 'success'
  | 'error'
  | 'cancelled';

export type FileProcessStatus = 'pending' | 'chunking' | 'embedding' | 'success' | 'error';

export const UPLOAD_STATUS_SET = new Set(['uploading', 'pending', 'processing']);

// the file that is upload at chat page
export interface UploadFileItem {
  /**
   * AbortController to cancel the upload
   */
  abortController?: AbortController;
  createdAt?: Date;
  /**
   * base64 data, it will use in other data
   */
  base64Url?: string;
  file: File;
  /**
   * the persisted file record id after upload succeeds
   */
  fileId?: string;
  /**
   * the file url after upload,it will be s3 url
   * if enable the S3 storage, or the data is same as base64Url
   */
  fileUrl?: string;
  id: string;
  /**
   * blob url for local preview
   * it will use in the file preview before send the message
   */
  previewUrl?: string;
  parentId?: string | null;
  sourceSetId?: string;
  spaceId?: string;
  status: FileUploadStatus;
  tasks?: FileParsingTask;
  uploadState?: FileUploadState;
}

export const FileMetadataSchema = z.object({
  date: z.string(),
  dirname: z.string(),
  filename: z.string(),
  path: z.string(),
});

export type FileMetadata = z.infer<typeof FileMetadataSchema>;

export const UploadFileSchema = z.object({
  /**
   * file type
   * @example 'image/png'
   */
  fileType: z.string(),
  sha256: z.string().min(1),

  sourceSetId: z.string().optional(),

  metadata: z.any().optional(),

  /**
   * file name
   * @example 'test.png'
   */
  name: z.string(),

  /**
   * file size
   */
  size: z.number(),

  /**
   * file source
   */
  source: z.string().optional(),

  /**
   * object storage key generated by the upload session
   */
  storageKey: z.string().min(1),
});

export type UploadFileParams = z.infer<typeof UploadFileSchema>;

export interface CheckSpaceBlobResult {
  fileType?: string;
  isExist: boolean;
  metadata?: unknown;
  size?: number;
  storageKey?: string;
}

export interface UploadBase64ToS3Result {
  fileType: string;
  sha256: string;
  metadata: FileMetadata;
  size: number;
}
