import type { ResourceContentActionsResult } from './useResourceContentActions';
import type { ResourceContentDataFlowResult } from './useResourceContentDataFlow';
import { useResourceContentOverlayAssembly } from './useResourceContentOverlayAssembly';
import type { ResourceContentStateResult } from './useResourceContentState';

interface UseResourceContentOverlayComposerProps {
  actions: ResourceContentActionsResult;
  dataFlow: ResourceContentDataFlowResult;
  state: ResourceContentStateResult;
}

export function useResourceContentOverlayComposer({
  actions,
  dataFlow,
  state,
}: UseResourceContentOverlayComposerProps) {
  return useResourceContentOverlayAssembly({
    attachment: {
      onClose: actions.upload.closeAttachmentSheet,
      onOpenCreateFolder: actions.folderActions.openCreateFolder,
      onPickDocument: actions.upload.handlePickFile,
      onPickGallery: actions.upload.handlePickPhoto,
      sourceSetId: state.scopeNavigation.sourceSetId,
      visible: actions.upload.attachmentSheetVisible,
    },
    createFolder: {
      onCancel: actions.folderActions.closeCreateFolder,
      onSubmit: actions.folderActions.handleCreateFolder,
      visible: actions.folderActions.createFolderVisible,
    },
    governance: {
      capabilityHint: dataFlow.surfaceData.governanceCapabilityHint,
      draftFilterCount: state.governance.draftGovernanceFilterCount,
      draftFilters: state.governance.governanceDraft,
      draftTokens: state.governance.governanceDraftTokens,
      enabled: state.governanceEnabled,
      hasDraftChanges: state.governance.hasGovernanceDraftChanges,
      onApply: state.governance.applyGovernanceFilters,
      onClearDraft: state.governance.clearGovernanceDraft,
      onClose: state.governance.closeGovernanceSheet,
      onRemoveDraftFilter: state.governance.removeGovernanceDraftFilter,
      onSetDraftFilters: state.governance.setGovernanceDraft,
      sections: state.governance.governanceSections,
      visible: state.governance.governanceSheetVisible,
    },
    headerMenus: {
      currentSortLabel: state.surfaceControls.sortLabel,
      dropdownHorizontalPadding: state.layout.dropdownHorizontalPadding,
      dropdownTopPadding: state.layout.dropdownTopPadding,
      headerMenuMinWidth: state.layout.headerMenuMinWidth,
      headerVisible: state.surfaceControls.headerMenuVisible,
      onCloseHeader: state.surfaceControls.closeHeaderMenu,
      onCloseSort: state.surfaceControls.closeSortMenu,
      onOpenSharedWithMe: state.previewShare.openSharedWithMe,
      onOpenSort: state.surfaceControls.openSortMenu,
      onOpenSourceSetManagement: actions.sourceSetControls.openSourceSetManagement,
      onOpenTrash: actions.trash.openTrash,
      onSelectSort: state.surfaceControls.handleSelectSort,
      sortMenuMinWidth: state.layout.sortMenuMinWidth,
      sortOrder: state.surfaceControls.sortOrder,
      sortVisible: state.surfaceControls.sortMenuVisible,
      sorter: state.surfaceControls.sorter,
      sourceSetSelected: !!state.scopeNavigation.sourceSetId,
    },
    itemAction: {
      actionItem: actions.selection.actionItem,
      hasAnySourceSets: state.sourceSetDerived.sourceSets.length > 0,
      inSourceSetScope: !!state.scopeNavigation.sourceSetId,
      onAddToChatContext: actions.selection.handleAddToChatContext,
      onClose: actions.selection.closeActionSheet,
      onConvertToDocument: actions.selection.handleConvertActionItemToDocument,
      onDeleteItem: actions.selection.handleDelete,
      onManageShare: actions.selection.handleManageShareFromItem,
      onMoveToFolder: actions.folderActions.openMoveToFolder,
      onOpenSourceSetAction: actions.sourceSetActions.openSourceSetAction,
      onPreviewItem: state.previewShare.handlePreview,
      onRemoveFromSourceSet: actions.sourceSetActions.handleRemoveFromSourceSet,
      onRename: actions.selection.handleRenameStart,
      onShare: actions.selection.handleShareFromActionSheet,
      otherSourceSetCount: state.sourceSetDerived.availableTargetSourceSets.length,
    },
    moveToFolder: {
      batchMoveCount: actions.folderActions.batchMoveCount,
      currentFolder: actions.folderActions.moveFolderCurrent ?? null,
      currentRootLabel: state.sourceSetDerived.currentSourceRootLabel,
      folders: actions.folderActions.moveTargetFolders,
      onBack: actions.folderActions.leaveMoveFolder,
      onClose: actions.folderActions.closeMoveToFolder,
      onEnterFolder: actions.folderActions.enterMoveFolder,
      onSelectFolder: actions.folderActions.handleMoveToFolder,
      stackDepth: actions.folderActions.moveFolderStackDepth,
      visible: actions.folderActions.moveToFolderVisible,
    },
    preview: {
      apiBaseUrl: dataFlow.collectionData.apiBase,
      initialCachedEntry: state.previewShare.previewItem
        ? (state.previewCache.cachedResourceMap[state.previewShare.previewItem.id] ?? null)
        : null,
      item: state.previewShare.previewItem,
      onCacheReady: state.previewCache.applyCachedResourceEntry,
      onClose: state.previewShare.closePreview,
      onReplaceItem: actions.selection.replaceResourceItem,
      origin: state.previewShare.previewOrigin,
      remoteHeaders: dataFlow.surfaceData.resourceAuthHeaders,
      visible: state.previewShare.previewVisible,
    },
    rename: {
      defaultValue: actions.selection.renameValue,
      onCancel: actions.selection.closeRenameModal,
      onSubmit: actions.selection.handleRenameSubmit,
      visible: actions.selection.renameModalVisible,
    },
    scopeLauncher: {
      activeSpaceId: state.scopeNavigation.activeSpaceId,
      currentSpaceName: state.currentSpaceName,
      groups: state.sourceSetDerived.sourceSetLauncherGroups,
      isAllFilesScope: state.scopeNavigation.isAllFilesScope,
      isUnassignedScope: state.scopeNavigation.isUnassignedScope,
      onChangeTab: state.scopeNavigation.setScopeLauncherTab,
      onClose: state.scopeNavigation.closeScopeLauncher,
      onCreateSourceSet: actions.sourceSetControls.openCreateSourceSetModal,
      onCreateSpace: state.spaceCreate.openCreateSpaceModal,
      onOpenSharedWithMe: state.previewShare.openSharedWithMe,
      onOpenSpaceMemory: state.headerControls.openScopeSpaceMemory,
      onOpenTrash: actions.trash.openTrash,
      onSelectAllFiles: () => state.scopeNavigation.applyFileScope('all'),
      onSelectSourceSet: state.scopeNavigation.switchToSourceSet,
      onSelectSpace: state.scopeNavigation.applySpaceSelection,
      onSelectUnassigned: () => state.scopeNavigation.applyFileScope('unassigned'),
      pendingSourceSetSelectionId: state.scopeNavigation.pendingSourceSetSelectionId,
      selectedSourceSetId: state.scopeNavigation.sourceSetId,
      selectedTab: state.scopeNavigation.scopeLauncherTab,
      showSpaceMemoryShortcut: state.spaces.currentSpace?.kind === 'team',
      spaces: state.spaces.spaces,
      visible: state.scopeNavigation.scopeLauncherVisible,
      workspaceTrashLabel: state.sourceSetDerived.workspaceTrashLabel,
    },
    share: {
      manageTarget: state.previewShare.manageShareTarget,
      onCloseManage: state.previewShare.closeManageShare,
      onCloseShare: state.previewShare.closeShare,
      onCloseSharedWithMe: state.previewShare.closeSharedWithMe,
      onPickSharedWithMe: actions.entryFlows.handleSharedWithMePick,
      optionTarget: state.previewShare.shareTarget,
      sharedWithMeVisible: state.previewShare.sharedWithMeVisible,
    },
    sourceSet: {
      actionMode: actions.sourceSetActions.sourceSetActionMode,
      actionSubmitting: actions.sourceSetActions.sourceSetActionSubmitting,
      actionVisible: actions.sourceSetActions.sourceSetActionVisible,
      id: state.scopeNavigation.sourceSetId,
      menuVisible: actions.sourceSetActions.sourceSetSharingMenuVisible,
      nameDraft: actions.sourceSetActions.sourceSetNameDraft,
      nameModalVisible: actions.sourceSetActions.sourceSetNameModalVisible,
      nameMode: actions.sourceSetActions.sourceSetNameMode,
      onCloseAction: actions.sourceSetActions.closeSourceSetAction,
      onCloseMenu: actions.sourceSetActions.closeSourceSetSharingMenu,
      onCloseNameModal: actions.sourceSetActions.closeSourceSetNameModal,
      onDelete: actions.sourceSetActions.handleDeleteSourceSet,
      onManageShare: state.previewShare.openManageShareForSourceSet,
      onRename: actions.sourceSetActions.openRenameSourceSetModal,
      onSelectTarget: actions.sourceSetActions.handleSelectSourceSetTarget,
      onShare: state.previewShare.openShareForSourceSet,
      onSubmitName: actions.sourceSetActions.handleSubmitSourceSetName,
      sourceSets: state.sourceSetDerived.availableTargetSourceSets,
    },
    spaceCreate: {
      descriptionDraft: state.spaceCreate.spaceCreateDescriptionDraft,
      nameDraft: state.spaceCreate.spaceCreateNameDraft,
      onChangeDescription: state.spaceCreate.setSpaceCreateDescriptionDraft,
      onChangeName: state.spaceCreate.setSpaceCreateNameDraft,
      onClose: state.spaceCreate.closeCreateSpaceModal,
      onSubmit: state.spaceCreate.handleCreateSpace,
      submitting: state.spaceCreate.spaceCreateSubmitting,
      visible: state.spaceCreate.spaceCreateVisible,
    },
    trash: {
      items: actions.trash.trashedDocuments,
      loading: actions.trash.trashLoading,
      onClose: actions.trash.closeTrash,
      onRestore: actions.trash.handleRestoreTrashed,
      restoringId: actions.trash.restoringTrashId,
      visible: actions.trash.trashModalVisible,
    },
  });
}
